version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
#    ports:
#      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      #Heart beat
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      #kafla container is depends on zookeeper container, so let the zookeeper start running first.
      - zookeeper
    environment:
      #set broker ID
      KAFKA_BROKER_ID: 1
      #referring to the container of Zookeeper by match the zookeeper container name above and its port
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      #define listener security protocol
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1